# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0006b9459f1ec538aa351e78e59bc42ca304fde5d4ae13ded6ad8877b005f383338699d87a67b7358cb715771a266a7da49c0d8505a6dc887959a0fb14a6b567

test:
  secret_key_base: 8e046fb30782b0157df575ee01693cb14dbe0e162b062fa9da8f8da3f55c9d6e49acc89f9c304c14c73022b3a176eb587ee9de0d70b80368a4b31a7f614fca62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
